version: 2
project_name: gocdm

builds:
  - id: gocdm
    main: ./cmd/gocdm
    binary: gocdm
    env:
      - CGO_ENABLED=1
    goos:
      - linux
    goarch:
      - amd64
      - arm64

  - id: gocdm-nopam
    main: ./cmd/gocdm
    binary: gocdm-nopam
    flags:
      - -tags=nopam
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64

archives:
  - id: gocdm
    builds:
      - gocdm
    format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    files:
      - license.txt
      - README.md
      - profile.sh
      - src: themes
        dst: themes

  - id: gocdm-nopam
    builds:
      - gocdm-nopam
    format: tar.gz
    name_template: >-
      {{ .ProjectName }}_nopam_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    files:
      - license.txt
      - README.md
      - profile.sh
      - src: themes
        dst: themes

nfpms:
  - id: gocdm
    builds:
      - gocdm
    formats:
      - deb
      - rpm
      - apk
    vendor: "gocdm"
    homepage: "https://github.com/arran4/gocdm"
    maintainer: "gocdm maintainers"
    description: "gocdm is a console display manager"
    license: "MIT"
    bindir: "/usr/local/bin"

  - id: gocdm-nopam
    package_name: gocdm-nopam
    builds:
      - gocdm-nopam
    formats:
      - deb
      - rpm
      - apk
    vendor: "gocdm"
    homepage: "https://github.com/arran4/gocdm"
    maintainer: "gocdm maintainers"
    description: "gocdm is a console display manager (without pam support)"
    license: "MIT"
    bindir: "/usr/local/bin"

checksum:
  name_template: 'checksums.txt'

release:
  mode: replace

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
