version: 2
project_name: gocdm

builds:
  - id: gocdm
    main: ./cmd/gocdm
    binary: gocdm
    env:
      - CGO_ENABLED=1
    goos:
      - linux
    goarch:
      - amd64
      - arm64

  - id: gocdm-nopam
    main: ./cmd/gocdm
    binary: gocdm-nopam
    flags:
      - -tags=nopam
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64

archives:
  - id: gocdm
    builds:
      - gocdm
    format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    files:
      - license.txt
      - README.md
      - profile.sh
      - src: themes
        dst: themes

  - id: gocdm-nopam
    builds:
      - gocdm-nopam
    format: tar.gz
    name_template: >-
      {{ .ProjectName }}_nopam_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    files:
      - license.txt
      - README.md
      - profile.sh
      - src: themes
        dst: themes

checksum:
  name_template: 'checksums.txt'

release:
  mode: replace

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
