// Code generated by github.com/arran4/go-subcommand/cmd/gosubc. DO NOT EDIT.

package main

import (
	"testing"
)

func TestRoot_Execute(t *testing.T) {
	cmd, err := NewRoot("test", "", "", "")
	if err != nil {
		t.Fatalf("Failed to create root command: %v", err)
	}

	called := false
	cmd.CommandAction = func(c *RootCmd) error {
		called = true
		return nil
	}

	args := []string{}
	args = append(args, "--dry-run")
	args = append(args, "--menu")

	err = cmd.Execute(args)
	if err != nil {
		t.Errorf("Unexpected error: %v", err)
	}
	if !called {
		t.Error("CommandAction was not called")
	}

	if cmd.dryRun != true {
		t.Errorf("Expected dryRun to be true, got '%v'", cmd.dryRun)
	}
	if cmd.forceMenu != true {
		t.Errorf("Expected forceMenu to be true, got '%v'", cmd.forceMenu)
	}

}
